Repository simonKoenig/recalc, pull requests merged in 2023-05, with the labels that each got.

#9 Agrega test de la función sub que devuelve un resultado negativo
  test/core.test.js
Labels: test

#11 Agrega test de la funcion multiply que devuelve un resultado negativo
  test/core.test.js
Labels: test

#12 Agrego test de la función pow que devuelve un resultado positivo
  test/core.test.js
Labels: test

#13 Se agrega la verificación y el test al dividir por 0
  src/core.js
  test/core.test.js
Labels: test

#14 Cambio el matcher del test de la funcion Pow
  test/core.test.js
Labels: test

#15 Cambio el matcher del Test de la funcion Multiply
  test/core.test.js
Labels: test

#17 Agrego el segundo argumento al momento de cargar un nuevo registro
  src/controllers.js
  src/models.js
  test/models.test.js
Labels: bug

#20 Agrego y testeo la funcion para borrar el historial
  src/controllers.js
  src/models.js
  test/models.test.js
Labels: feature

#21 Arreglo errores menores
  src/core.js
  test/api.test.js
Labels: fix

#22 Agrego y testeo persistencia al realizar la operacion add
  src/controllers.js
  test/api.test.js
Labels: feature

#23 Agrego persistencia y test a la función mul
  src/controllers.js
  test/api.test.js
Labels: feature

#25 Feature/div persistir
  src/controllers.js
  test/api.test.js
Labels: feature

#26 Soluciono problemas de mergeo
  test/api.test.js
Labels: bug
