Repository simonKoenig/recalc, pull requests merged in 2023-06, with the labels that each got.

#28 Corrección del test para comprobar resultado con decimales en mul
  test/api.test.js
Labels: bug

#29 Agrego test para comprobar que el historial se borra correctamente
  test/models.test.js
Labels: feature

#30 Modifico el test para probar la funcion obtenerHistorial
  test/models.test.js
Labels: feature

#31 Agrego la funcion para obtener el historial por id
  src/controllers.js
  src/models.js
Labels: feature

#32 Agrego test de la funcion obtenerHistorialPorID
  test/models.test.js
Labels: test

#34 Agrego y testeo la función mul en el frontend
  src/public/index.js
  test/ui.test.js
Labels: feature

#35 Agrego y testeo la función de división al frontend
  src/public/index.js
  test/ui.test.js
Labels: feature

#36 Agrego y testeo botón de potencia en el frontend
  src/public/index.html
  src/public/index.js
  test/ui.test.js
Labels: feature

#38 Release v1.3.3
  .eslintrc.cjs
  CHANGELOG.md
  README.md
  package.json
  src/api.js
  src/cli.js
  src/controllers.js
  src/core.js
  src/models.js
  src/public/index.html
  src/public/index.js
  test/api.test.js
  test/core.test.js
  test/models.test.js
  test/ui.test.js
Labels: feature
